//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlpataAmatörKüme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupBilgis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupBilgis()
        {
            this.TakimBilgis = new HashSet<TakimBilgis>();
        }
    
        public int Grupid { get; set; }
        public string GrupAdi { get; set; }
        public int Takimid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakimBilgis> TakimBilgis { get; set; }
    }
}
