//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlpataAmatörKüme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuanBilgis
    {
        public int Puanid { get; set; }
        public string Puan { get; set; }
        public string Galibiyet { get; set; }
        public string Beraberlik { get; set; }
        public string Malubiyet { get; set; }
        public string Averaj { get; set; }
        public string AtilanGol { get; set; }
        public string YenilenGol { get; set; }
        public int Takimid { get; set; }
    
        public virtual TakimBilgis TakimBilgis { get; set; }
    }
}
