//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlpataAmatörKüme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakimBilgis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TakimBilgis()
        {
            this.PuanBilgis = new HashSet<PuanBilgis>();
            this.GrupBilgis = new HashSet<GrupBilgis>();
        }
    
        public int Takimid { get; set; }
        public string Takimİsmi { get; set; }
        public string TakimBilgisi { get; set; }
        public string TakimAdresi { get; set; }
        public string TakimTel { get; set; }
        public string TakimLogo { get; set; }
        public string TakimBaskan { get; set; }
        public int Grupid { get; set; }
        public string GrupAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuanBilgis> PuanBilgis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupBilgis> GrupBilgis { get; set; }
    }
}
